TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

DEFINES += _POSIX_SOURCE  _STRUCT_TIMESPEC

LIBS += -Lpthread

QMAKE_CFLAGS += -DHAVE_STRUCT_TIMESPEC

INCLUDEPATH += \
        include/

SOURCES += \
    test/cpu/cpus-mask-test.c \
    test/lib/ptr-test.c \
    test/sched/rq-test.c \
    main.c \
    test/sched/decay_load.c \
    test/sched/taskset.c \
    test/sched/update_load_avg.c \
    kernel/sched/core.c \
    kernel/sched/pelt.c \
    lib/string.c \
    lib/math/div64.c \
    mm/slab_user.c \
    kernel/sched/deadline.c \
    kernel/sched/fair.c \
    kernel/sched/rt.c \
    kernel/sched/stats.c \
    kernel/sched/clock.c \
    kernel/sched/completion.c \
    kernel/sched/core.c \
    kernel/sched/cpuacct.c \
    kernel/sched/cpudeadline.c \
    kernel/sched/cpufreq.c \
    kernel/sched/cpupri.c \
    kernel/sched/cputime.c \
    kernel/sched/deadline.c \
    kernel/sched/fair.c \
    kernel/sched/idle.c \
    kernel/sched/loadavg.c \
    kernel/sched/pelt.c \
    kernel/sched/rt.c \
    kernel/sched/stats.c \
    kernel/sched/stop_task.c \
    kernel/sched/swait.c \
    kernel/sched/topology.c \
    kernel/sched/wait.c

HEADERS += \
    include/test/test.h \
    include/linux/list.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/poison.h \
    include/linux/proc_fs.h \
    include/linux/rbtree_augmented.h \
    include/linux/rbtree.h \
    include/linux/rcu.h \
    include/linux/refcount.h \
    include/linux/ring_buffer.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/time64.h \
    include/linux/zalloc.h \
    include/asm/alternative-asm.h \
    include/asm/atomic.h \
    include/asm/barrier.h \
    include/asm/bug.h \
    include/asm/export.h \
    include/asm/sections.h \
    include/asm-generic/bitops/__ffs.h \
    include/asm-generic/bitops/__ffz.h \
    include/asm-generic/bitops/__fls.h \
    include/asm-generic/bitops/arch_hweight.h \
    include/asm-generic/bitops/atomic.h \
    include/asm-generic/bitops/const_hweight.h \
    include/asm-generic/bitops/find.h \
    include/asm-generic/bitops/fls.h \
    include/asm-generic/bitops/fls64.h \
    include/asm-generic/bitops/hweight.h \
    include/asm-generic/bitops/non-atomic.h \
    include/asm-generic/atomic-gcc.h \
    include/asm-generic/barrier.h \
    include/asm-generic/bitops.h \
    include/asm-generic/bitsperlong.h \
    include/asm-generic/hugetlb_encode.h \
    include/linux/sched/clock.h \
    include/linux/sched/task.h \
    include/linux/unaligned/packed_struct.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/poison.h \
    include/linux/proc_fs.h \
    include/linux/rbtree.h \
    include/linux/rbtree_augmented.h \
    include/linux/rcu.h \
    include/linux/refcount.h \
    include/linux/ring_buffer.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/time64.h \
    include/linux/zalloc.h \
    include/uapi/asm/bitsperlong.h \
    include/uapi/asm/bpf_perf_event.h \
    include/uapi/asm/errno.h \
    include/uapi/asm-generic/bitsperlong.h \
    include/uapi/asm-generic/bpf_perf_event.h \
    include/uapi/asm-generic/errno-base.h \
    include/uapi/asm-generic/errno.h \
    include/uapi/asm-generic/fcntl.h \
    include/uapi/asm-generic/ioctls.h \
    include/uapi/asm-generic/mman-common-tools.h \
    include/uapi/asm-generic/mman-common.h \
    include/uapi/asm-generic/mman.h \
    include/uapi/asm-generic/socket.h \
    include/uapi/asm-generic/unistd.h \
    include/uapi/drm/drm.h \
    include/uapi/drm/i915_drm.h \
    include/uapi/linux/tc_act/tc_bpf.h \
    include/uapi/linux/bpf.h \
    include/uapi/linux/bpf_common.h \
    include/uapi/linux/bpf_perf_event.h \
    include/uapi/linux/btf.h \
    include/uapi/linux/const.h \
    include/uapi/linux/erspan.h \
    include/uapi/linux/ethtool.h \
    include/uapi/linux/fadvise.h \
    include/uapi/linux/fcntl.h \
    include/uapi/linux/fs.h \
    include/uapi/linux/fscrypt.h \
    include/uapi/linux/hw_breakpoint.h \
    include/uapi/linux/if_link.h \
    include/uapi/linux/if_tun.h \
    include/uapi/linux/if_xdp.h \
    include/uapi/linux/in.h \
    include/uapi/linux/kcmp.h \
    include/uapi/linux/kvm.h \
    include/uapi/linux/lirc.h \
    include/uapi/linux/mman.h \
    include/uapi/linux/mount.h \
    include/uapi/linux/netlink.h \
    include/uapi/linux/perf_event.h \
    include/uapi/linux/pkt_cls.h \
    include/uapi/linux/pkt_sched.h \
    include/uapi/linux/prctl.h \
    include/uapi/linux/sched.h \
    include/uapi/linux/seg6.h \
    include/uapi/linux/seg6_local.h \
    include/uapi/linux/stat.h \
    include/uapi/linux/tls.h \
    include/uapi/linux/usbdevice_fs.h \
    include/uapi/linux/vhost.h \
    include/uapi/sound/asound.h \
    include/test/config.h \
    include/linux/sched.h \
    include/linux/cache.h \
    include/asm-generic/cache.h \
    include/linux/compiler_types.h \
    include/linux/cpumask.h \
    include/linux/threads.h \
    include/linux/restart_block.h \
    include/linux/pid.h \
    include/linux/rculist.h \
    include/linux/wait.h \
    include/linux/spinlock_types_up.h \
    include/linux/spinlock_types.h \
    include/linux/rwlock.h \
    include/linux/rwlock_types.h \
    include/linux/slab.h \
    include/asm-generic/word-at-a-time.h \
    include/asm-generic/page.h \
    include/asm-generic/memory_model.h \
    include/asm-generic/getorder.h \
    include/linux/mm.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/cache.h \
    include/linux/compiler_types.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/cpumask.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/idr.h \
    include/linux/init.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/mm.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/percpu.h \
    include/linux/pid.h \
    include/linux/poison.h \
    include/linux/preempt.h \
    include/linux/proc_fs.h \
    include/linux/radix-tree.h \
    include/linux/rbtree_augmented.h \
    include/linux/rbtree.h \
    include/linux/rcu.h \
    include/linux/rculist.h \
    include/linux/rcupdate.h \
    include/linux/refcount.h \
    include/linux/restart_block.h \
    include/linux/ring_buffer.h \
    include/linux/rwlock_api_smp.h \
    include/linux/rwlock_types.h \
    include/linux/rwlock.h \
    include/linux/sched.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/slab.h \
    include/linux/spinlock_types_up.h \
    include/linux/spinlock_types.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/threads.h \
    include/linux/time64.h \
    include/linux/wait.h \
    include/linux/xarray.h \
    include/linux/zalloc.h \
    include/linux/pfn.h \
    kernel/sched/sched.h \
    kernel/sched/pelt.h \
    kernel/sched/sched-pelt.h \
    include/linux/seqlock.h \
    include/linux/llist.h \
    include/linux/plist.h \
    include/linux/sched/prio.h \
    include/linux/sched/sysctl.h \
    include/linux/math64.h \
    include/asm-generic/div64.h \
    include/linux/cgroup.h \
    include/linux/kernel_stat.h \
    include/linux/sched/autogroup.h \
    include/linux/radix-tree.h \
    include/linux/radix-tree-user.h \
    kernel/sched/stats.h \
    include/test/debug.h \
    include/linux/sched/topology.h \
    include/linux/topology.h \
    include/linux/arch_topology.h \
    include/linux/sched/idle.h \
    include/linux/sched/autogroup.h \
    include/linux/sched/clock.h \
    include/linux/sched/coredump.h \
    include/linux/sched/cpufreq.h \
    include/linux/sched/deadline.h \
    include/linux/sched/debug.h \
    include/linux/sched/hotplug.h \
    include/linux/sched/idle.h \
    include/linux/sched/init.h \
    include/linux/sched/isolation.h \
    include/linux/sched/jobctl.h \
    include/linux/sched/loadavg.h \
    include/linux/sched/nohz.h \
    include/linux/sched/numa_balancing.h \
    include/linux/sched/prio.h \
    include/linux/sched/rt.h \
    include/linux/sched/smt.h \
    include/linux/sched/stat.h \
    include/linux/sched/sysctl.h \
    include/linux/sched/task_stack.h \
    include/linux/sched/task.h \
    include/linux/sched/topology.h \
    include/linux/sched/types.h \
    include/linux/sched/user.h \
    include/linux/sched/wake_q.h \
    include/linux/sched/xacct.h \
    include/uapi/linux/sched/types.h \
    kernel/sched/autogroup.h \
    kernel/sched/cpudeadline.h \
    kernel/sched/cpupri.h \
    kernel/sched/features.h \
    kernel/sched/pelt.h \
    kernel/sched/sched-pelt.h \
    kernel/sched/sched.h \
    kernel/sched/stats.h \
    include/test/define-usr.h \
    include/linux/smp.h \
    include/linux/thread_info.h \
    include/linux/smp.h \
    include/asm-generic/current.h \
    include/asm/thread_info.h \
    include/asm/current.h \
    include/asm-generic/percpu.h \
    include/linux/percpu-defs.h \
    include/linux/seqlock.h \
    include/linux/types-user.h \
    include/linux/ktime.h \
    include/linux/jiffies.h \
    include/generated/timeconst.h \
    include/linux/typecheck.h \
    include/uapi/asm-generic/signal.h \
    include/uapi/asm-generic/signal-defs.h \
    include/linux/rwlock_types.h \
    include/linux/hrtimer.h \
    include/linux/sched_clock.h \
    include/linux/errno.h \
    include/uapi/linux/errno.h \
    include/linux/completion.h \
    include/linux/cgroup-defs.h \
    include/linux/kernel_stat.h \
    include/linux/cpuhotplug.h \
    include/linux/swait.h
