TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

unix|win32: LIBS += -lpthread

INCLUDEPATH += \
        include/

SOURCES += \
    test/cpu/cpus-mask-test.c \
    test/lib/ptr-test.c \
    test/sched/rq-test.c \
    main.c

HEADERS += \
    include/test/test.h \
    include/linux/list.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/poison.h \
    include/linux/proc_fs.h \
    include/linux/rbtree_augmented.h \
    include/linux/rbtree.h \
    include/linux/rcu.h \
    include/linux/refcount.h \
    include/linux/ring_buffer.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/time64.h \
    include/linux/types.h \
    include/linux/zalloc.h \
    include/asm/alternative-asm.h \
    include/asm/atomic.h \
    include/asm/barrier.h \
    include/asm/bug.h \
    include/asm/export.h \
    include/asm/sections.h \
    include/asm-generic/bitops/__ffs.h \
    include/asm-generic/bitops/__ffz.h \
    include/asm-generic/bitops/__fls.h \
    include/asm-generic/bitops/arch_hweight.h \
    include/asm-generic/bitops/atomic.h \
    include/asm-generic/bitops/const_hweight.h \
    include/asm-generic/bitops/find.h \
    include/asm-generic/bitops/fls.h \
    include/asm-generic/bitops/fls64.h \
    include/asm-generic/bitops/hweight.h \
    include/asm-generic/bitops/non-atomic.h \
    include/asm-generic/atomic-gcc.h \
    include/asm-generic/barrier.h \
    include/asm-generic/bitops.h \
    include/asm-generic/bitsperlong.h \
    include/asm-generic/hugetlb_encode.h \
    include/linux/sched/clock.h \
    include/linux/sched/mm.h \
    include/linux/sched/task.h \
    include/linux/unaligned/packed_struct.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/poison.h \
    include/linux/proc_fs.h \
    include/linux/rbtree.h \
    include/linux/rbtree_augmented.h \
    include/linux/rcu.h \
    include/linux/refcount.h \
    include/linux/ring_buffer.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/time64.h \
    include/linux/types.h \
    include/linux/zalloc.h \
    include/uapi/asm/bitsperlong.h \
    include/uapi/asm/bpf_perf_event.h \
    include/uapi/asm/errno.h \
    include/uapi/asm-generic/bitsperlong.h \
    include/uapi/asm-generic/bpf_perf_event.h \
    include/uapi/asm-generic/errno-base.h \
    include/uapi/asm-generic/errno.h \
    include/uapi/asm-generic/fcntl.h \
    include/uapi/asm-generic/ioctls.h \
    include/uapi/asm-generic/mman-common-tools.h \
    include/uapi/asm-generic/mman-common.h \
    include/uapi/asm-generic/mman.h \
    include/uapi/asm-generic/socket.h \
    include/uapi/asm-generic/unistd.h \
    include/uapi/drm/drm.h \
    include/uapi/drm/i915_drm.h \
    include/uapi/linux/tc_act/tc_bpf.h \
    include/uapi/linux/bpf.h \
    include/uapi/linux/bpf_common.h \
    include/uapi/linux/bpf_perf_event.h \
    include/uapi/linux/btf.h \
    include/uapi/linux/const.h \
    include/uapi/linux/erspan.h \
    include/uapi/linux/ethtool.h \
    include/uapi/linux/fadvise.h \
    include/uapi/linux/fcntl.h \
    include/uapi/linux/fs.h \
    include/uapi/linux/fscrypt.h \
    include/uapi/linux/hw_breakpoint.h \
    include/uapi/linux/if_link.h \
    include/uapi/linux/if_tun.h \
    include/uapi/linux/if_xdp.h \
    include/uapi/linux/in.h \
    include/uapi/linux/kcmp.h \
    include/uapi/linux/kvm.h \
    include/uapi/linux/lirc.h \
    include/uapi/linux/mman.h \
    include/uapi/linux/mount.h \
    include/uapi/linux/netlink.h \
    include/uapi/linux/perf_event.h \
    include/uapi/linux/pkt_cls.h \
    include/uapi/linux/pkt_sched.h \
    include/uapi/linux/prctl.h \
    include/uapi/linux/sched.h \
    include/uapi/linux/seg6.h \
    include/uapi/linux/seg6_local.h \
    include/uapi/linux/stat.h \
    include/uapi/linux/tls.h \
    include/uapi/linux/usbdevice_fs.h \
    include/uapi/linux/vhost.h \
    include/uapi/sound/asound.h \
    include/test/config.h \
    include/linux/sched.h \
    include/linux/cache.h \
    include/asm-generic/cache.h \
    include/linux/compiler_types.h \
    include/linux/cpumask.h \
    include/linux/threads.h \
    include/linux/restart_block.h \
    include/linux/pid.h \
    include/linux/rculist.h \
    include/linux/wait.h \
    include/linux/spinlock_types_up.h \
    include/linux/spinlock_types.h \
    include/linux/rwlock.h \
    include/linux/rwlock_types.h \
    include/linux/slab.h \
    include/asm-generic/word-at-a-time.h \
    include/asm-generic/page.h \
    include/asm-generic/memory_model.h \
    include/asm-generic/getorder.h \
    include/linux/mm.h \
    include/linux/atomic.h \
    include/linux/bitmap.h \
    include/linux/bitops.h \
    include/linux/bits.h \
    include/linux/bug.h \
    include/linux/cache.h \
    include/linux/compiler_types.h \
    include/linux/compiler-gcc.h \
    include/linux/compiler.h \
    include/linux/const.h \
    include/linux/coresight-pmu.h \
    include/linux/cpumask.h \
    include/linux/ctype.h \
    include/linux/debug_locks.h \
    include/linux/delay.h \
    include/linux/err.h \
    include/linux/export.h \
    include/linux/filter.h \
    include/linux/ftrace.h \
    include/linux/gfp.h \
    include/linux/hardirq.h \
    include/linux/hash.h \
    include/linux/hashtable.h \
    include/linux/idr.h \
    include/linux/init.h \
    include/linux/interrupt.h \
    include/linux/irqflags.h \
    include/linux/jhash.h \
    include/linux/kallsyms.h \
    include/linux/kern_levels.h \
    include/linux/kernel.h \
    include/linux/linkage.h \
    include/linux/list.h \
    include/linux/lockdep.h \
    include/linux/log2.h \
    include/linux/mm.h \
    include/linux/module.h \
    include/linux/mutex.h \
    include/linux/nmi.h \
    include/linux/numa.h \
    include/linux/overflow.h \
    include/linux/percpu.h \
    include/linux/pid.h \
    include/linux/poison.h \
    include/linux/preempt.h \
    include/linux/proc_fs.h \
    include/linux/radix-tree.h \
    include/linux/rbtree_augmented.h \
    include/linux/rbtree.h \
    include/linux/rcu.h \
    include/linux/rculist.h \
    include/linux/rcupdate.h \
    include/linux/refcount.h \
    include/linux/restart_block.h \
    include/linux/ring_buffer.h \
    include/linux/rwlock_api_smp.h \
    include/linux/rwlock_types.h \
    include/linux/rwlock.h \
    include/linux/sched.h \
    include/linux/seq_file.h \
    include/linux/sizes.h \
    include/linux/slab_def.h \
    include/linux/slab.h \
    include/linux/spinlock_types_up.h \
    include/linux/spinlock_types.h \
    include/linux/spinlock.h \
    include/linux/stacktrace.h \
    include/linux/string.h \
    include/linux/stringify.h \
    include/linux/threads.h \
    include/linux/time64.h \
    include/linux/types.h \
    include/linux/wait.h \
    include/linux/xarray.h \
    include/linux/zalloc.h \
    include/nolibc/nolibc.h \
    include/linux/pfn.h \
    kernel/sched/sched.h
